### ISSUE TITLE
please update the permission_handler dependency

### ISSUE THREAD

**Issue by ArizArmeidi** [Subhi-Khalife/social_media_recorder#10]
>Because social_media_recorder 0.1.84 depends on permission_handler ^9.2.0 and no versions of social_media_recorder match >0.1.84 <0.2.0, social_media_recorder ^0.1.84 requires permission_handler ^9.2.0. So, because (my app) depends on both permission_handler ^10.2.0 and social_media_recorder ^0.1.84, version solving failed.

please update the permission_handler package to the latest version, thanks.

**Comment by Subhi-Khalife** [comment]
Hello @ArizArmeidi 
Update to new version please

**Comment by ArizArmeidi** [comment]
Thanks for the quick response
