### ISSUE TITLE
Operation not permitted Exception because of not valid path in real android device

### ISSUE THREAD

**Issue by abdelrahmanelmarakby** [Subhi-Khalife/social_media_recorder#13]
https://github.com/Subhi-Khalife/social_media_recorder/blob/b65ac21e2649e3a930ff82de97907838de6d69e2/lib/provider/sound_record_notifier.dart#L126
I got a Operation not permitted Exception error:1 because in android you set the path to "Storage/0/emulated"!! which is not a valid path except for emulators

**Comment by abdelrahmanelmarakby** [comment]
I fixed the issue in this pull request [Not valid path in real android device](https://github.com/Subhi-Khalife/social_media_recorder/pull/14#issue-1517204678)

**Comment by Subhi-Khalife** [comment]
@abdelrahmanelmarakby Thanks bro

**Comment by abdelrahmanelmarakby** [comment]
@Subhi-Khalife keep the good work✨
