### ISSUE TITLE
Error when compiling

### ISSUE THREAD

**Issue by watchyy** [Subhi-Khalife/social_media_recorder#15]
Hello. First of all, I am a total newbie to code and while trying to compile the recorder widget in my app as a widget on flutterflow, I keep getting the message that these 2 items as seen from the picture are not defined. 

I have done my best to ensure that I have all the code and dependencies added but it is yet to solve the problem. Kindly let me know how to solve it or where the problem is located.
Thanks alot

![scrnli_2_25_2023_8-26-55 AM](https://user-images.githubusercontent.com/126332434/221358438-72d58550-6a63-40ec-9632-ed66c890ea53.png)

**Comment by Subhi-Khalife** [comment]
Hello @watchyy 
Can you try this solution from stackOverFlow 
https://stackoverflow.com/questions/55740952/error-the-getter-ltr-isnt-defined-for-the-class-textdirection
because this error from direction import

**Comment by watchyy** [comment]
> Hello @watchyy Can you try this solution from stackOverFlow https://stackoverflow.com/questions/55740952/error-the-getter-ltr-isnt-defined-for-the-class-textdirection because this error from direction import

Hello. Thanks alot for the quick response. I have solved the text direction issue the only problem left is that it indicates that there are some erorrs with the widget code but when I open the dialogue box for details, it is empty. I am confused. are there code or not? Any idea
Thank you once again

**Comment by Subhi-Khalife** [comment]
> > Hello @watchyy Can you try this solution from stackOverFlow https://stackoverflow.com/questions/55740952/error-the-getter-ltr-isnt-defined-for-the-class-textdirection because this error from direction import
> 
> Hello. Thanks alot for the quick response. I have solved the text direction issue the only problem left is that it indicates that there are some erorrs with the widget code but when I open the dialogue box for details, it is empty. I am confused. are there code or not? Any idea Thank you once again

@watchyy you are welcome 
I didn't get you well for new issue can you send code or image for more details
