### ISSUE TITLE
Recording doesnt start from first time

### ISSUE THREAD

**Issue by KhaledAbdElNasserAhmed** [Subhi-Khalife/social_media_recorder#19]
When I click on record icon, it doesn't start recording immediately, I have to click it another time for it to actually start recording.

**Comment by Subhi-Khalife** [comment]
Hello @KhaledAbdElNasserAhmed 
check permission if OK then the record will start record directly

**Comment by dogukanatakul** [comment]
I'm having the same problem. It has nothing to do with permission!

**Comment by Subhi-Khalife** [comment]
@dogukanatakul 
did you add permissions that added inside Readme ?
