### ISSUE TITLE
i have 2 issues

### ISSUE THREAD

**Issue by rulefahd** [Subhi-Khalife/social_media_recorder#2]
it's not customizable enough , i cant fix the overflow on the right side , and  it keeps crashing every other time when recording ?

can you fix the overflow ? , 
and when i try to use the widget with Stack , it show a circle in the middle , that cant be removed or given a transpernt color 

thank you

**Comment by Subhi-Khalife** [comment]
> it's not customizable enough , i cant fix the overflow on the right side , and it keeps crashing every other time when recording ?
> 
> can you fix the overflow ? , and when i try to use the widget with Stack , it show a circle in the middle , that cant be removed or given a transpernt color
> 
> thank you

hello 
i will fix all the errors in the nearest time and i will tell you when all problem fixed

**Comment by waqarmkhani** [comment]
> it's not customizable enough , i cant fix the overflow on the right side , and it keeps crashing every other time when recording ?
> 
> can you fix the overflow ? , and when i try to use the widget with Stack , it show a circle in the middle , that cant be removed or given a transpernt color
> 
> thank you

same issue 
Please fixed it

**Comment by Subhi-Khalife** [comment]
@rulefahd give me your code with Stack because i tried multi time and no error showed

**Comment by Subhi-Khalife** [comment]
@rulefahd @waqarmkhani 
overflow problem fixed and make the mic scrolling more smoothly 
just update to new version
