### ISSUE TITLE
why first press cannot start recoder

### ISSUE THREAD

**Issue by yydsapi** [Subhi-Khalife/social_media_recorder#22]
why first press cannot start recoder(no lock icon),  and no problem in the future

thank you ! this is my code:

Align(
              alignment: Alignment.centerLeft,
              child: SocialMediaRecorder(
              textVisible:textVisible,
                sendRequestFunction: (soundFile) {
                  //print("the current path is ${soundFile.path}");
                },
                encode: AudioEncoderType.AAC,
              ),

**Comment by Subhi-Khalife** [comment]
Hello @yydsapi 
Because in the first press i check permission for record and storage if the permissions done 
So the record and all functions will work well 
So if you face any issue check permissions that added in readme pubdev package section for android and ios

**Comment by yydsapi** [comment]
Thank you for your answer！
