### ISSUE TITLE
Incompatible with audioplayers >=3.0.1

### ISSUE THREAD

**Issue by blablabla123-cell** [Subhi-Khalife/social_media_recorder#23]
I try to install the last version of the package and I get this output:

Because social_media_recorder >=0.3.0 depends on uuid ^4.0.0 and audioplayers >=3.0.1 depends on uuid ^3.0.7, social_media_recorder >=0.3.0 is incompatible with audioplayers >=3.0.1.
So, because we_do_osm_flutter depends on both audioplayers ^5.0.0 and social_media_recorder ^0.3.31, version solving failed.

You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on social_media_recorder: flutter pub add social_media_recorder:^0.1.32
exit code 1

**Comment by Subhi-Khalife** [comment]
Hello @blablabla123-cell 
i uploaded new version 
social_media_recorder: ^0.3.32
if you have any issue tell me

**Comment by blablabla123-cell** [comment]
Thank you, seems like it works now

**Comment by Subhi-Khalife** [comment]
@blablabla123-cell you're welcome
