### ISSUE TITLE
Record Icon Size and Locked Record Icon Size

### ISSUE THREAD

**Issue by blablabla123-cell** [Subhi-Khalife/social_media_recorder#24]
Hey, there. I am styling the media recorder matching it with my application theme using  my own icons set. Please add functionality to resize the icons in each state. Also is it available to change the width of the whole media recorder so that you could resize it. Like dragging left to cancel seems very short to me, I would like to expand it little bit so the user would drag little longer to cancel recording. Thanks for the amazing package you provided in advance!

**Comment by blablabla123-cell** [comment]
I found out that there is no limit in recording as well. Would be awesome adding it. So that the user can't hold it for longer than 2 minutes or so

**Comment by blablabla123-cell** [comment]
Oh. sorry, I was using SVGs and I noticed that if I use a normal Icon(Ions.sed, size: 24) it works, but if I use SvgPicture.asset(SVGs.send, heigh: 24, width: 24) it didn't

**Comment by blablabla123-cell** [comment]
I found solution for this, using IconButton(icon: SvgPicture.asset(SVGs.send, width: 24, height: 24), onPressed: null).

**Comment by Subhi-Khalife** [comment]
@blablabla123-cell 
Thanks for Great suggestions i will work on it ASAP 
and i will upload new version

**Comment by Subhi-Khalife** [comment]
Hello @blablabla123-cell 

i uploaded updates with new release 1.0.0 

check latest version please if you have any things tell me
