### ISSUE TITLE
Cancel function

### ISSUE THREAD

**Issue by Yaliih** [Subhi-Khalife/social_media_recorder#25]
Thank you very much for this work which makes our lives easier... a question how can I know that a recording has just been canceled ?

**Comment by Subhi-Khalife** [comment]
Hello @Yaliih 
can you update to latest version 1.0.0 and check stopRecording function 
i call this function when user press cancle or slide to max left or user need to send audio sound 
check it please and if you need any change tell me

**Comment by Yaliih** [comment]
Thank you it works very well now. But this caused another problem since by holding the button for recording after releasing the stopRecording function is not called

**Comment by Subhi-Khalife** [comment]
you're welcome @Yaliih 
can you check again please because stopRecording  call when user press on send button after lock record or when leave finger from record button

**Comment by Yaliih** [comment]
Thank you  @Subhi-Khalife
 
Yes you are right it was linked to a problem with my codes otherwise it works very well. 

I am now thinking about how to add pause and play before sending the recorded message

**Comment by Subhi-Khalife** [comment]
@Yaliih 
you're welcome 
you can make it like inside sendRequestFunction you can take the file path and show record with pause and paly button 
when user press send you can send message else ignore it

**Comment by Yaliih** [comment]
@Subhi-Khalife You are an angel thank you!

Lots of love !
