### ISSUE TITLE
Overflow Issue and audio not playing

### ISSUE THREAD

**Issue by kostricanitechnology** [Subhi-Khalife/social_media_recorder#26]
Hello, 
I am getting an overflow on the right and cannot see the send button. Also when I send the voice I cannot play it.

**Comment by Subhi-Khalife** [comment]
Hello @kostricanitechnology 
Can you check permissions if added well  ? And Can you send your code section please

**Comment by kostricanitechnology** [comment]
hello, 

I added all the permissions as per the documentation. Im not sure if the code will help but here it is

`Builder(builder: (context) {
                                        return GestureDetector(
                                            onLongPress: () {
                                              setState(() {
                                                showsheet = true;
                                              });
                                            },
                                            onLongPressEnd: (details) {
                                              Navigator.pop(context);
                                            },
                                            onTap: () {
                                              Okitel.toast(
                                                  'Hold to Record Audio, Tap to switch Video');
                                              setState(() {
                                                showvideo = false;
                                              });
                                            },
                                            child: Stack(
                                              children: [
                                                Icon(Icons.video_camera_back,
                                                    color: Colors.blue,
                                                    size: 30),
                                              ],
                                            ));
                                      }`

Also there is the overflow issue with it.

**Comment by Subhi-Khalife** [comment]
In this code you don't use my package @kostricanitechnology

**Comment by kostricanitechnology** [comment]
Sorry, I have sent the wrong one. Here is your code

`RecordButton(
                                            releaseToSend: true,
                                            color: Colors.blue,
                                            size: 35,
                                            recordButtonColor: okitelchatgreen,
                                            recordBgColor:
                                                Color.fromARGB(0, 255, 255, 255),
                                            allTextColor: Colors.white,
                                            controller: controler!,
                                            arrowColor: Colors.white,
                                            onRecordEnd: (String value) {
                                              setState(() {
                                                filepath = value;
                                                readOnly = true;
                                              });
                                              getFileData(File(filepath));
                                              onSendMessage(
                                                  context,
                                                  filepath.toString() +
                                                      '-BREAK-' +
                                                      DateTime.now()
                                                          .millisecondsSinceEpoch
                                                          .toString(),
                                                  MessageType.audio,
                                                  DateTime.now()
                                                      .millisecondsSinceEpoch);
                                            },
                                            onRecordStart: () {
                                              setState(() {
                                                readOnly = false;
                                              });
                                            },
                                            onCancelRecord: () {
                                              setState(() {
                                                readOnly = false;
                                              });
                                            },
                                          )`

**Comment by kostricanitechnology** [comment]
when i send the voice from Android to Android it works, when I send from Android to iPhone it doesn't work and also from iPhone to Android it doesn't work as well

**Comment by Subhi-Khalife** [comment]
@kostricanitechnology 
Are you sure you used my own package ?
This code not for my package my own package link
https://pub.dev/packages/social_media_recorder
Can you check again please

**Comment by kostricanitechnology** [comment]
Sorry I got confused, there are two packages with same name. Here is your code

`Align(
                                        alignment: Alignment.centerLeft,
                                        child: SocialMediaRecorder(
                                          // maxRecordTimeInSecond: 5,
                                          startRecording: () {
                                            setState(() {
                                              showunshow = true;
                                            });
                                          },
                                          stopRecording: (_time) {
                                            setState(() {
                                              showunshow = false;
                                            });
                                          },
                                          sendRequestFunction:
                                              (soundFile, _time) {
                                            print(
                                                "the current path is ${soundFile.path}");
                                            getFileData(File(soundFile.path));
                                            onSendMessage(
                                                context,
                                                soundFile.path +
                                                    '-BREAK-' +
                                                    DateTime.now()
                                                        .millisecondsSinceEpoch
                                                        .toString(),
                                                MessageType.audio,
                                                DateTime.now()
                                                    .millisecondsSinceEpoch);
                                          },
                                          encode: AudioEncoderType.AAC,
                                        ),
                                      )`

**Comment by Subhi-Khalife** [comment]
@kostricanitechnology 
Over flow show because you put centerLeft and unfortunately package support only from right to left from now 
But for File if it's work on android or ios it should work on several devices can you check file please and check what the style it send throw server 
Because it's file should work in same for both without any diffrent

**Comment by kostricanitechnology** [comment]
let me try and will let you know

**Comment by Subhi-Khalife** [comment]
OK

**Comment by kostricanitechnology** [comment]
the output on the database is like this /cache/2024-01-24-13:38.m4a I think the format is wrong

**Comment by Subhi-Khalife** [comment]
Can you check file inside your phone please if will work well or not
If work well then the issue not from file else from file

**Comment by kostricanitechnology** [comment]
On my phone I cannot play it. The message send but cannot be played

**Comment by Subhi-Khalife** [comment]
I saved all sound inside save directory you can found there all your records
