### ISSUE TITLE
Overflow Issue

### ISSUE THREAD

**Issue by rajam1215** [Subhi-Khalife/social_media_recorder#27]
@Subhi-Khalife i used your library, its giving me overflow error, 
![Screenshot_20240220-173205](https://github.com/Subhi-Khalife/social_media_recorder/assets/16591300/3752b338-9920-41e8-b9a6-1deadc1badf0)

My code is 

     Widget _msgFooter(BuildContext context, ConversationProvider provider) {
    bool isvisible = status != 'Closed' ? true : false;
    return Visibility(
      visible: isvisible,
      child: Container(
        padding: const EdgeInsets.symmetric(vertical: 8, horizontal: 14),
        decoration: const BoxDecoration(
          color: Color.fromARGB(255, 226, 226, 226),
        ),
        child: Row(
          children: [
            Expanded(child: _inputMsg(provider)),
            _icons(context, provider),
          ],
        ),
      ),
    );
     }
     
     Widget _inputMsg(ConversationProvider provider) {
    return TextField(
      controller: provider.messageController,
      decoration: const InputDecoration.collapsed(
        hintText: 'Type a Message....',
      ),
      onChanged: (text) => provider.setMessage(text),
    );
    }
  
  
  
    Widget _icons(BuildContext context, ConversationProvider provider) {
    return Row(
      children: [
        const Space(horizontal: 10),
        _sendAudio(context, provider),
        const Space(horizontal: 10),
        _sendImage(context, provider),
        const Space(horizontal: 10),
        _sendMessage(context, provider),
      ],
    );
    }

     Widget _sendAudio(BuildContext context, ConversationProvider provider) {
    return Align(
      alignment: Alignment.centerRight,
      child: SocialMediaRecorder(
        recordIcon: const Icon(Icons.mic_none_outlined),
        sendRequestFunction: (soundFile, time) {
          print('sound file - ${soundFile.path}');
        },
        encode: AudioEncoderType.AAC,
      ),
    );
     }
     
      Widget _sendImage(BuildContext context, ConversationProvider provider) {
    return InkWell(
      child: SvgPicture.asset(
        'assets/icons/camera.svg',
        height: 28.0,
        width: 28.0,
        colorFilter:
            const ColorFilter.mode(Constants.COLOUR_PRIMARY, BlendMode.srcIn),
      ),
      onTap: () => _onAddCameraClick(context, provider),
    );
     }
     
       Widget _sendMessage(BuildContext context, ConversationProvider provider) {
    String message = provider.message;
    return InkWell(
      child: SvgPicture.asset(
        'assets/icons/send.svg',
        height: 32.0,
        width: 32.0,
        colorFilter: ColorFilter.mode(
            message.isNotEmpty
                ? Constants.COLOUR_PRIMARY
                : Constants.COLOUR_DISABLE,
            BlendMode.srcIn),
      ),
      onTap: () {
        if (message.isNotEmpty) {
          _performSendMsg(context, provider);
        }
      },
    );
      }
  
  when i use only _sendAudio function _msgFooter widget function then error is not occur

**Comment by rajam1215** [comment]
@Subhi-Khalife please reply on this.

**Comment by Subhi-Khalife** [comment]
Hello @rajam1215 
can you check your Row please 
because as i think OverFlow come from Row with Space if you can use Expanded and Flexible with Row 
or give static width for package option 
try this solution and tell me

**Comment by rajam1215** [comment]
@Subhi-Khalife I can't understand, can you please elaborate the code, my code is there, please check once

**Comment by Subhi-Khalife** [comment]
@rajam1215 
i can't make update in your code because it's have special class but i mean code will be like this 
`
 Column(
            
              mainAxisAlignment: MainAxisAlignment.start,
            
              crossAxisAlignment: CrossAxisAlignment.center,
            
              mainAxisSize: MainAxisSize.min,
            
              children: [
            
                Row(
              
                  mainAxisAlignment: MainAxisAlignment.end,
              
                  children: [
              
                    Icon(Icons.abc),
              
                    Flexible(
              
                      child: SocialMediaRecorder(
              
                        // maxRecordTimeInSecond: 5,
              
                        startRecording: () {
              
                          // function called when start recording
              
                        },
              
                        stopRecording: (_time) {
              
                          // function called when stop recording, return the recording time
              
                        },
              
                        sendRequestFunction: (soundFile, _time) {
              
                          //  print("the current path is ${soundFile.path}");
              
                        },
              
                        encode: AudioEncoderType.AAC,
              
                      ),
              
                    ),
              
                  ],
              
                ),
              
              ],
           
            ),
 
            `

**Comment by rajam1215** [comment]
@Subhi-Khalife I did this in my code, but it is not working

**Comment by rajam1215** [comment]
@Subhi-Khalife I use this code in my code, but it is not working, still issue persist, you can use my code in dummy project, please check how to solve.

**Comment by Subhi-Khalife** [comment]
If you can update your code without classes and send full screen here please to check it @rajam1215

**Comment by rajam1215** [comment]
@Subhi-Khalife 

       import 'package:flutter/material.dart';
       import 'package:flutter_svg/flutter_svg.dart';
     import 'package:image_picker/image_picker.dart';
      import 'package:provider/provider.dart';
      import 'package:social_media_recorder/audio_encoder_type.dart';
     import 'package:social_media_recorder/screen/social_media_recorder.dart';
     import 'package:voice_message_package/voice_message_package.dart';
     import '../models/conversation.dart';
     import '../models/response.dart';
     import '../providers/providers.dart';
     import '../utilities/constants.dart';
     import '../utilities/formatter.dart';
     import '../widgets/alert.dart';
     import '../widgets/loader.dart';
     import '../widgets/spacer.dart';
     import 'image_zoom.dart';

      // ignore_for_file: avoid_print, use_build_context_synchronously
       class ConversationScreen extends StatelessWidget {
      final int? id;
      final String? status, userType;

       const ConversationScreen(
        {super.key,
        required this.id,
        required this.status,
        required this.userType});

     @override
       Widget build(BuildContext context) {
      print('Drawing Conversation Screen');
      Provider.of<ConversationProvider>(context, listen: false)
        .fetchConversation(id);
      return Scaffold(
      appBar: _appBar(),
      body: SafeArea(
        child: _body(),
      ),
      backgroundColor: Colors.white,
    );
     }

    PreferredSizeWidget _appBar() {
    return AppBar(
      title: const Text(
        'Messages',
        style: TextStyle(color: Colors.black),
      ),
    );
     }

       Widget _body() {
    return Consumer<ConversationProvider>(
      builder: (context, provider, child) {
        if (provider.isLoading) {
          return _loader();
        } else {
          dynamic data = provider.chatResponse;
          if (data is List<ConversationModel>?) {
            return _uiBuilder(context, provider, data ?? []);
          } else if (data is ErrorResponseModel) {
            return _errorMessage(data.message);
          } else {
            return _errorMessage('Something went wrong');
          }
        }
      },
    );
      }

    Widget _loader() {
    print('Drawing Loader');
    return Center(
      child: Loader.loader(),
    );
    }

    Widget _errorMessage(String message) {
    print('Drawing error');
    return Center(
      child: Text(message),
    );
    }

     Widget _uiBuilder(BuildContext context, ConversationProvider provider,
      List<ConversationModel> data) {
    return Column(
      children: [
        Expanded(child: _conversation(provider, data)),
        _msgFooter(context, provider),
      ],
    );
    }

    Widget _conversation(
      ConversationProvider provider, List<ConversationModel> conversation) {
    if (conversation.isNotEmpty) {
      WidgetsBinding.instance.addPostFrameCallback((_) {
        provider.scrollController
            .jumpTo(provider.scrollController.position.maxScrollExtent);
      });
      return ListView.builder(
          controller: provider.scrollController,
          itemCount: conversation.length,
          itemBuilder: (context, index) {
            return _message(context, conversation[index]);
          });
    } else {
      return _errorMessage('You did not have any conversation');
    }
    }

    Widget _message(BuildContext context, ConversationModel conversation) {
    return Container(
      margin: const EdgeInsets.symmetric(vertical: 8.0, horizontal: 10.0),
      child: (conversation.messageFrom != userType)
          ? _msgWith(context, conversation)
          : _msgOwn(context, conversation),
    );
    }

    Widget _msgWith(BuildContext context, ConversationModel conversation) {
    return Align(
      alignment: Alignment.centerLeft,
      child: Container(
        padding: const EdgeInsets.symmetric(vertical: 8.0, horizontal: 10.0),
        decoration: BoxDecoration(
          color: const Color.fromARGB(255, 240, 240, 240),
          border: Border.all(color: Colors.white, width: 1.0),
          borderRadius: const BorderRadius.all(Radius.circular(12.0)),
        ),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            _desc(context, conversation),
            const Space(vertical: 10),
            _date(conversation.createdAt ?? ''),
          ],
        ),
      ),
    );
    }

    Widget _msgOwn(BuildContext context, ConversationModel conversation) {
    return Align(
      alignment: Alignment.centerRight,
      child: Container(
        padding: const EdgeInsets.symmetric(vertical: 8.0, horizontal: 10.0),
        decoration: BoxDecoration(
          color: Constants.COLOUR_PRIMARY,
          border: Border.all(color: Colors.white, width: 1.0),
          borderRadius: const BorderRadius.all(Radius.circular(12.0)),
        ),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.end,
          children: [
            _desc(context, conversation),
            const Space(vertical: 10),
            _date(conversation.createdAt ?? ''),
          ],
        ),
      ),
    );
    }

    Widget _desc(BuildContext context, ConversationModel conversation) {
    String descType = conversation.descriptionType ?? '';
    String desc = conversation.description ?? '';
    if (descType == 'text') {
      String msgFrom = conversation.messageFrom ?? '';
      return Text(
        desc,
        style: TextStyle(
          color: msgFrom != userType ? Colors.black : Colors.white,
          fontSize: 15,
        ),
      );
    } else if (descType == 'image') {
      return GestureDetector(
        onTap: () => Navigator.of(context).push(MaterialPageRoute(
            builder: (context) => ImageZoomScreen(desc: desc))),
        child: ClipRRect(
          borderRadius: BorderRadius.circular(8.0),
          child: Image.network(desc,
              fit: BoxFit.cover, width: 200.0, height: 200.0),
        ),
      );
    } else {
      return VoiceMessageView(
        controller: VoiceController(
          audioSrc: desc,
          maxDuration: const Duration(seconds: 10),
          isFile: false,
          onComplete: () {},
          onPause: () {},
          onPlaying: () {},
        ),
        cornerRadius: 8,
      );
    }
    }

    Widget _date(String date) {
    return Text(
      Formatter.dateFormat(date),
      style: const TextStyle(
        color: Color.fromARGB(255, 179, 179, 179),
        fontSize: 10,
      ),
    );
    }

    Widget _msgFooter(BuildContext context, ConversationProvider provider) {
    bool isvisible = status != 'Closed' ? true : false;
    return Visibility(
      visible: isvisible,
      child: Container(
        padding: const EdgeInsets.symmetric(vertical: 8, horizontal: 14),
        decoration: const BoxDecoration(
          color: Color.fromARGB(255, 226, 226, 226),
        ),
        child: Row(
          children: [
            Expanded(child: _inputMsg(provider)),
            _icons(context, provider),
          ],
        ),
      ),
    );
    }

    Widget _inputMsg(ConversationProvider provider) {
    return TextField(
      controller: provider.messageController,
      decoration: const InputDecoration.collapsed(
        hintText: 'Type a Message....',
      ),
      onChanged: (text) => provider.setMessage(text),
    );
    }

    Widget _icons(BuildContext context, ConversationProvider provider) {
    return Row(
      mainAxisSize: MainAxisSize.max,
      children: [
        const Space(horizontal: 10),
        _sendAudio(context, provider),
        const Space(horizontal: 10),
        _sendImage(context, provider),
        const Space(horizontal: 10),
        _sendMessage(context, provider),
      ],
    );
    }

    Widget _sendAudio(BuildContext context, ConversationProvider provider) {
    return Align(
      alignment: Alignment.centerRight,
      child: SocialMediaRecorder(
        recordIcon: const Icon(Icons.mic_none_outlined),
        sendRequestFunction: (soundFile, time) {
          if (soundFile.path.isNotEmpty) {
            print('sound file - ${soundFile.path}');
            // _performSendFile(context, provider, 'audio', soundFile.path);
          }
        },
        encode: AudioEncoderType.AAC,
      ),
    );
    }

    Widget _sendImage(BuildContext context, ConversationProvider provider) {
    return InkWell(
      child: SvgPicture.asset(
        'assets/icons/camera.svg',
        height: 28.0,
        width: 28.0,
        colorFilter:
            const ColorFilter.mode(Constants.COLOUR_PRIMARY, BlendMode.srcIn),
      ),
      onTap: () => _onAddCameraClick(context, provider),
    );
    }

    void _onAddCameraClick(
      BuildContext context, ConversationProvider provider) async {
    XFile? pickedFile = await ImagePicker().pickImage(
      source: ImageSource.camera,
      imageQuality: 10,
    );
    if (pickedFile != null) {
      _performSendFile(context, provider, 'image', pickedFile.path);
    }
    }

    Widget _sendMessage(BuildContext context, ConversationProvider provider) {
    String message = provider.message;
    return InkWell(
      child: SvgPicture.asset(
        'assets/icons/send.svg',
        height: 32.0,
        width: 32.0,
        colorFilter: ColorFilter.mode(
            message.isNotEmpty
                ? Constants.COLOUR_PRIMARY
                : Constants.COLOUR_DISABLE,
            BlendMode.srcIn),
      ),
      onTap: () {
        if (message.isNotEmpty) {
          _performSendMsg(context, provider);
        }
      },
    );
    }

    void _performSendFile(BuildContext context, ConversationProvider provider,
      String description, String path) async {
    Loader.showLoading(context);
    final res = await provider.sendFile(id, description, path);
    Navigator.pop(context);
    if (res is SuccessResponseModel) {
      print(res.message);
    } else if (res is ErrorResponseModel) {
      Alert.basic(context, res.message);
    } else {
      Alert.basic(context, 'Something went wrong, Please try again later');
    }
    }

    void _performSendMsg(
      BuildContext context, ConversationProvider provider) async {
    Loader.showLoading(context);
    final res = await provider.sendMessage(id);
    Navigator.pop(context);
    if (res is SuccessResponseModel) {
      provider.clearFields();
    } else if (res is ErrorResponseModel) {
      Alert.basic(context, res.message);
    } else {
      Alert.basic(context, 'Something went wrong, Please try again later');
    }
    }
    }

**Comment by rajam1215** [comment]
@Subhi-Khalife please check out what is the major cause for the overflow issue.

**Comment by Subhi-Khalife** [comment]
@rajam1215 
as i told you check your _icons function and use flexible and expanded and it should work well

**Comment by Subhi-Khalife** [comment]
use Text instead my package and it show overflow
so the error from responsive and row issue

**Comment by rajam1215** [comment]
> @rajam1215 as i told you check your _icons function and use flexible and expanded and it should work well

@Subhi-Khalife It is not working with flexible and expended i already check many time.

**Comment by rajam1215** [comment]
@Subhi-Khalife any solution, otherwise this library have so many bugs.
