### ISSUE TITLE
Problem on saving file above and Android 11

### ISSUE THREAD

**Issue by Mamasodikov** [Subhi-Khalife/social_media_recorder#29]
On android 11 and above you can't name files with ":"
Please fix file naming, i changed the codes and finally I can save my audio:

`convertedDateTime = convertedDateTime.replaceAll(":", ".");`

Reference: https://stackoverflow.com/questions/61406818/filenotfoundexception-open-failed-eperm-operation-not-permitted-during-saving

**Comment by Subhi-Khalife** [comment]
Hello @Mamasodikov 
Thanks for fix
Sure some hours and i will check and Upload new version again
