### ISSUE TITLE
Overflow Issue after start recording

### ISSUE THREAD

**Issue by waqarmkhani** [Subhi-Khalife/social_media_recorder#3]
When I start recording it show button overflow by 40 pixel 
Please fixed the issue.
and please check the attached snapshot
![WhatsApp Image 2022-03-10 at 2 29 57 PM](https://user-images.githubusercontent.com/8510306/157632652-be0733fb-2157-4c8b-a9c4-5fcc267ea65e.jpeg)
.

**Comment by Subhi-Khalife** [comment]
i will fix it and tell you when done

**Comment by waqarmkhani** [comment]
Dear **Subhi-Khalife** I am still waiting for your reply 
Please fixed it I need it urgent.....

**Comment by Subhi-Khalife** [comment]
@waqarmkhani 
I am very sorry for late 
All problems fixed 
Just update to new version
