### ISSUE TITLE
[doubt] Is possible to Record a mp3 file with social_media_recorder

### ISSUE THREAD

**Issue by EuHigorBarbosa** [Subhi-Khalife/social_media_recorder#5]
Is possible with this package to record a mp3 file from microphone on Android and IOS? If yes, with which AudioEncoder?

**Comment by Subhi-Khalife** [comment]
hello @EuHigorBarbosa 
i am very sorry for mp3 type because some error happened in mp3 so i removed it from this package
but i will try again for to add mp3 to this package

**Comment by EuHigorBarbosa** [comment]
Ok, thanks a lot...
