### ISSUE TITLE
permission_handler dependency

### ISSUE THREAD

**Issue by RoyalCoder88** [Subhi-Khalife/social_media_recorder#6]
Thanks for your package, please update the permission_handler dependency:

```Because every version of social_media_recorder depends on permission_handler ^8.1.6 and myapp depends on permission_handler ^9.2.0, social_media_recorder is forbidden.```

**Comment by Subhi-Khalife** [comment]
@RoyalCoder88 
Sure now i will update it

**Comment by Subhi-Khalife** [comment]
@RoyalCoder88 
update done you can check it

**Comment by RoyalCoder88** [comment]
@Subhi-Khalife thanks brother you are the best!
