### ISSUE TITLE
When i upload recorded audio using this package upload as MP4 not sound file or mp3

### ISSUE THREAD

**Issue by MarwanCS** [Subhi-Khalife/social_media_recorder#7]
i used MultiPartFile with dio to upload file
MultipartFile audioFile = await MultipartFile.fromFile(filePath.path);

how can i upload recorded File as audio not mp4?

**Comment by Subhi-Khalife** [comment]
Hello @MarwanCS 
Can you share the code please

**Comment by MarwanCS** [comment]
Hello @Subhi-Khalife thanks for reply
when audio recording done i called this function to upload the audio file to REST api with laravel
the file uploaded succefully but as .mp4 when the file extention in locally is fine and .m4a

The Widget Code
`SocialMediaRecorder(
                                       
                                        sendRequestFunction: (soundFile) async {
                                        
                                          await VoiceMessageController
                                              .uploadFile(soundFile);
                                       
                                        },
                                        encode: AudioEncoderType.AAC,
                                      ),`


The Function to upload
`  
static Future uploadFile(file) async {
    MultipartFile audioFile = await MultipartFile.fromFile(file.path);

    try {
      FormData formData = new FormData.fromMap({"audio": audioFile});
      Response response = await Dio().post(Shared.serverApi + 'Chats',
          data: formData,
          options: Options(headers: <String, String>{
            'Content-type': 'application/json',
            'Accept': 'application/json',
            'Authorization': 'Bearer ${Shared.laravel_user_token}',
          }));

      return response;
    } on DioError catch (e) {
      showDialogResult(Icons.error, "something_wrong".tr);
      return e.response;
    } catch (e) {}
  }`

**Comment by Subhi-Khalife** [comment]
@MarwanCS 
I tried multi time but the package return only two file type
1- 3gp when AMR_WB
2- m4a other cases
but until now i face error with .mp3 so my package not support mp3 type

**Comment by Subhi-Khalife** [comment]
@MarwanCS 
but for .MP4 my package not return this type
print soundFile to check end file path

**Comment by MarwanCS** [comment]
Thanks @Subhi-Khalife  Maybe the problem is from MultipartFile , Thank you for your help

**Comment by Subhi-Khalife** [comment]
@MarwanCS 
You are welcome
